package jakarta;

public class ConstantsJakarta {
    public static final String API = "/api";
    public static final String MESSAGE = "message";
    public static final String FECHA = "fecha";
    public static final String LOGIN = "/login";
    public static final String USERNAME = "username";
    public static final String PASSWORD = "password";
    public static final String EMPTY = "";
    public static final String EL_USUARIO_O_LA_CONTRASENA_SON_INCORRECTOS = "El usuario o la contraseña son incorrectos";
    public static final String EL_REGISTRO_NO_PUDO_SER_COMPLETADO = "El registro no pudo ser completado";
    public static final String FORGOTPASSWORD = "/forgotPassword";
    public static final String CORREO_ENVIADO = "Correo enviado";
    public static final String EL_CORREO_NO_ES_VALIDO = "El correo no es válido";
    public static final String REFRESHTOKEN = "/refreshToken";
    public static final String ALGORITHM_SHA_512 = "SHA-512";
    public static final String CLAVE = "clave";
    public static final String ALGORITHM_AES = "AES";
    public static final String ISSUER_SELF = "self";
    public static final String ROL = "rol";
    public static final String PERSONAJES = "/personajes";
    public static final String ROL_ADMIN = "Admin";
    public static final String ROL_USER = "User";
    public static final String PATH_ID = "/{id}";
    public static final String ID = "id";
    public static final String PATH_ID_VIDEOJUEGO = "/{idVideojuego}";
    public static final String ID_VIDEOJUEGO = "idVideojuego";
    public static final String REFRESH_TOKEN = "refreshToken";
    public static final String HA_HABIDO_UN_PROBLEMA_AL_GENERAR_EL_NUEVO_ACCESS_TOKEN = "Ha habido un problema al generar el nuevo accessToken";
    public static final String VIDEOJUEGOS = "/videojuegos";
    public static final String SERVLET_ACTIVATION = "ServletActivation";
    public static final String ACTIVATION = "/Activation";
    public static final String CODIGO = "codigo";
    public static final String CUENTA_ACTIVADA = "Cuenta activada";
    public static final String LA_CREDENCIAL_QUE_SE_HA_TRATADO_DE_ACTIVAR_NO_EXISTE = "La credencial que se ha tratado de activar no existe";
    public static final String SERVLET_CHANGE_PASSWORD = "ServletChangePassword";
    public static final String CHANGE_PASSWORD = "/ChangePassword";
    public static final String CONTRASENA_CAMBIADA = "Contraseña cambiada";
    public static final String NUEVA_CONTRASENA = "Nueva contraseña: ";
    public static final String HA_HABIDO_UN_ERROR_AL_TRATAR_DE_CAMBIAR_LA_CONTRASENA = "Ha habido un error al tratar de cambiar la contraseña";
    public static final String BEARER = "Bearer";
    public static final String USERLOGIN = "USERLOGIN";
    public static final String STATUS = "status";
    public static final String EL_TOKEN_DE_ACCESO_HA_EXPIRADO_SE_VA_A_GENERAR_OTRO = "El token de acceso ha expirado. Se va a generar otro";
    public static final String AUTHORIZATION = "Authorization";
    public static final String HUBO_UN_PROBLEMA = "Hubo un problema";
}
