package com.example.graphql.utils;

public class Constantes {
    public static final String KEYSTORE_PFX = "keystore.pfx";
    public static final String RSA = "RSA";
    public static final String CN_SERVER = "CN=Server";
    public static final String PKCS_12 = "PKCS12";
    public static final String SHA_256_WITH_RSA_ENCRYPTION = "SHA256WithRSAEncryption";
    public static final String CN = "CN=";
    public static final String SERVER = "server";
    public static final String USUARIO_O_CONTRASENA_INCORRECTOS = "Usuario o contraseña incorrectos.";
    public static final String HAY_CAMPOS_VACIOS = "Hay campos vacíos.";
    public static final String USUARIO_ANADIDO_CORRECTAMENTE = "Usuario añadido correctamente.";
    public static final String ID = "id";
    public static final String NOMBRE = "nombre";
    public static final String PROGRAMA_AGREGADO_CORRECTAMENTE = "Programa agregado correctamente.";
    public static final String CONTRASENA = "contrasena";
    public static final String SELECCIONA_UN_PROGRAMA_DE_LA_LISTA = "Selecciona un programa de la lista.";
    public static final String PBKDF_2_WITH_HMAC_SHA_256 = "PBKDF2WithHmacSHA256";
    public static final String AES = "AES";
    public static final String AES_GCM_NO_PADDING = "AES/GCM/noPadding";
    public static final String KEY_STORE_PASSWORD = "KeyStorePassword";
    public static final String NAME = "config/config.properties";
    public static final String ALERT = "alert";
    public static final String BTN_OK = "btn-ok";
    public static final String MENU_ACCOUNT_LOGOUT = "menuAccountLogout";
    public static final String ERROR_CON_LA_CONTRASENA = "Error con la contraseña";
    public static final String ERROR_AL_ENCONTRAR_EL_USUARIO = "Error al encontrar el usuario";
    public static final String USERNAME = "username";
    public static final String EL_CAMPO_ESTA_SIN_COMPLETAR = "El campo está sin completar";
    public static final String CONTRASENA_CAMBIADA_CORRECTAMENTE = "Contraseña cambiada correctamente";
    public static final String ASYM = "asym";
    public static final String FIRMA = "firma";
    public static final String SHA_256_WITH_RSA = "SHA256WithRSA";
    public static final String PERMISO_ANADIDO_CON_EXITO = "Permiso añadido con éxito";
    public static final String PERMISOS = "permisos";
    public static final String USER_NAME = "user_name";
    public static final String PROGRAMA_ID = "programa_id";
    public static final String NAMEUSER = "name";
    public static final String PASSWORD = "password";
    public static final String USER = "user";
    public static final String USUARIOS = "usuarios";
    public static final String PROGRAMAS = "programas";
    public static final String VARCHAR_500 = "varchar(500)";
    public static final String USER_ID = "user_id";
    public static final String PROGRAMA = "programa";
    public static final String FXML_LOGINREGISTRO_FXML = "/fxml/loginregistro.fxml";
    public static final String FXML_PROGRAMASPERMISOS_FXML = "/fxml/programaspermisos.fxml";
    public static final String FXML_PRINCIPAL_FXML = "/fxml/principal.fxml";
}
